name: ci

on:
  pull_request:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.4.0

      - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v2.1.5
        with:
          go-version: 1.18
          check-latest: true

      - name: build
        run: |
          make apko
          ./apko version

      - uses: goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef # v2.8.1
        with:
          version: latest
          install-only: true

      - name: snapshot
        run: |
          make snapshot
          ./dist/apko-build_linux_amd64_v1/apko version
