
name: Create Release

on:
  push:
    branches:
    - main
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  GO_VERSION: 1.18

jobs:
  cli:
    # Only release CLI for tagged releases
    if: startsWith(github.event.ref, 'refs/tags/v')

    name: Release the CLI
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v2.2.0
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0

    - uses: sigstore/cosign-installer@7e0881f8fe90b25e305bbf0309761e9314607e25 # v2.3.0

    - uses: goreleaser/goreleaser-action@ff11ca24a9b39f2d36796d1fbd7a4e39c182630a # v2.8.1
      with:
        version: latest
        install-only: true

    - name: Release
      run: make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ko-build:
    name: Release apko image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    env:
      KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
      COSIGN_EXPERIMENTAL: "true"

    steps:
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v2.2.0
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true

    - uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675 # v0.4

    - uses: sigstore/cosign-installer@7e0881f8fe90b25e305bbf0309761e9314607e25 # v2.3.0

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0

    - name: Login to registry
      run: |
        echo ${{ github.token }} | go run ./ login ghcr.io --username=${{ github.repository_owner }} --password-stdin

    - name: Publish/Sign apko image
      run: |
        # If not a tagged release, override image tag to "canary"
        if [[ $GITHUB_REF != refs/tags/* ]]; then
          export GIT_VERSION=canary
        fi
        make sign-image

  tekton-task:
    # Only release the Tekton Task after a CLI release has been created, since
    # goreleaser creates a GitHub Release which the Tekton Task will be
    # attached to.
    needs: cli

    name: Release the Tekton Task
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v2.2.0
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true

    - uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675 # v0.4

    - uses: sigstore/cosign-installer@7e0881f8fe90b25e305bbf0309761e9314607e25 # v2.3.0

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0

    - name: Login to registry
      run: |
        echo ${{ github.token }} | go run ./ login ghcr.io --username=${{ github.repository_owner }} --password-stdin

    - name: Generate Tekton Task
      run: |
        # If not a tagged release, override image tag to "canary"
        if [[ $GITHUB_REF != refs/tags/* ]]; then
          export GIT_VERSION=canary
        fi
        make ko-resolve

    - name: Attach to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${GITHUB_REF#refs/tags/} task.yaml
